name: Release workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "VERSION=$(echo $GITHUB_REF_NAME | tr -d 'v')" >> $GITHUB_ENV
      - name: Build and Publish
        run: |
          echo $VERSION
